# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoCrap < Formula
  desc "go-crap a CLI tool that calculates the CRAP score for Go projects"
  homepage "https://github.com/padiazg/go-crap"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/padiazg/go-crap/releases/download/v0.4.1/go-crap_0.4.1_darwin_amd64.tar.gz"
      sha256 "50ec314632f77e70f62494ec236514b4d6df1493bccad83615a5668da1ec5717"

      define_method(:install) do
        bin.install "go-crap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/padiazg/go-crap/releases/download/v0.4.1/go-crap_0.4.1_darwin_arm64.tar.gz"
      sha256 "b3c1ce41eb8cb459f12aadfcbf0579e9797df045022a4d160f7a995ad06336eb"

      define_method(:install) do
        bin.install "go-crap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/padiazg/go-crap/releases/download/v0.4.1/go-crap_0.4.1_linux_amd64.tar.gz"
      sha256 "7e886d75ac93acb69964c15f4cabe55336c294c7ef333de176fedbfdc2442b99"
      define_method(:install) do
        bin.install "go-crap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/padiazg/go-crap/releases/download/v0.4.1/go-crap_0.4.1_linux_arm64.tar.gz"
      sha256 "7e475361c89393b34dbb6ec514543416ea46720a20ef6a06b091020220fb4062"
      define_method(:install) do
        bin.install "go-crap"
      end
    end
  end
end
