# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-crap" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "23e3ed6d4705952b1148a4240738b6f5eab75ae72e37f8ba6909dd77f57719e5"
      url "https://github.com/padiazg/go-crap/releases/download/v#{version}/go-crap_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "67432679f9e2f5765d17a841f7ecba3fbc8970c1cd2d123085e6fd1c9d68df32"
      url "https://github.com/padiazg/go-crap/releases/download/v#{version}/go-crap_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "700dab07877ed5e43777557b503359465cdc247c02abe4d2f7088ea620ccfd1e"
      url "https://github.com/padiazg/go-crap/releases/download/v#{version}/go-crap_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a0fa30fac8076a605f042ad4ac3d942d5e4edd6ebe7db7ddabbf849a4aba3c89"
      url "https://github.com/padiazg/go-crap/releases/download/v#{version}/go-crap_#{version}_linux_arm64.tar.gz"
    end
  end

  name "go-crap"
  desc "go-crap a CLI tool that calculates the CRAP score for Go projects"
  homepage "https://github.com/padiazg/go-crap"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-crap"

  # No zap stanza required

end
