# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-crap" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "397576885296beaa852c5880bb0000710ae10490c863fa8c5ad0ef8c41ca8fff"
      url "https://github.com/padiazg/go-crap/releases/download/v#{version}/go-crap_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a3930c7e01c0a43e95ddb1bad9295c8a7ad86ae1e7ba2ec7ccbf77b970ab7cb4"
      url "https://github.com/padiazg/go-crap/releases/download/v#{version}/go-crap_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e5b8d8543c9f39ae39340ef707ff53ea481945b710b01e34b96e00150491606d"
      url "https://github.com/padiazg/go-crap/releases/download/v#{version}/go-crap_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a27afe7c618346208b19112426d45202a48658ebfd59e06b05e75bdf0ffd7c29"
      url "https://github.com/padiazg/go-crap/releases/download/v#{version}/go-crap_#{version}_linux_arm64.tar.gz"
    end
  end

  name "go-crap"
  desc "go-crap a CLI tool that calculates the CRAP score for Go projects"
  homepage "https://github.com/padiazg/go-crap"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-crap"

  # No zap stanza required

end
