# This file was generated by GoReleaser. DO NOT EDIT.
cask "go-crap" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "3506da3ebec70cc972e7f7aa9454e1d2296371382b050d1dedabec2e9222ffde"
      url "https://github.com/padiazg/go-crap/releases/download/v#{version}/go-crap_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4fe581044409103e8ea5e8fff06273c259cbfb0b9f3aea02349c57b76b992545"
      url "https://github.com/padiazg/go-crap/releases/download/v#{version}/go-crap_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a344ef8c3182f2788d3569b9366bb9d62e6350fde52bff5aab52e6e9b4e73a44"
      url "https://github.com/padiazg/go-crap/releases/download/v#{version}/go-crap_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "12cdabdf7ae20774f6d9006a36f4d438aa134a72a14e020015790fd959aa3233"
      url "https://github.com/padiazg/go-crap/releases/download/v#{version}/go-crap_#{version}_linux_arm64.tar.gz"
    end
  end

  name "go-crap"
  desc "go-crap a CLI tool that calculates the CRAP score for Go projects"
  homepage "https://github.com/padiazg/go-crap"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "go-crap"

  # No zap stanza required

end
